### ISSUE TITLE
Apache Troubleshooting documentation is confusing

### ISSUE THREAD

**Issue by kravlin** [gotify/website#62]
Hi. I don't know where else to submit this, so I'm gonna do it here.

under the troubleshooting section on https://gotify.net/docs/apache the documentation is kind of confusing. It's stream of consciousness with the "Proxy requests with sub path" section and when implementing the fix the "/gotify/stream" should only be "/stream" if you're not using subpaths. 

I'm not sure how exactly to fix this except to provide a better example such as "STREAM_DIR" or similar, and there's not really a documentation repo or I'd create a pull request.

Thanks!

**Comment by jmattheis** [comment]
The docs are right inside this repo -> https://github.com/gotify/website/blob/master/docs/apache.md

I understand the confusion, but Gotify doesn't really need to provide a tutorial on how to do everything with every possible config combination. I'd expect the user to have some basic knowledge of what they are doing. So I think this is good enough.
