### ISSUE TITLE
Update Google Play badge

### ISSUE THREAD

**Issue by cyb3rko** [gotify/website#73]
I think it's a good idea to update the Google Play badge as there's an updated and more modern looking one.
Atm the website uses locally stored pngs, maybe just implement a link so the badge is always up-to-date.

Here's the badge generator:
https://play.google.com/intl/en_us/badges/

The linking could be done with the F-Droid badge as well if you want to:
https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

**Comment by jmattheis** [comment]
I'd like to keep third-party requests to a minimum. It's just more data, that google can use to track us (:.
