### ISSUE TITLE
IPv6 support for gotify.net

### ISSUE THREAD

**Issue by n-thumann** [gotify/website#77]
I've noticed that gotify.net isn't reachable via IPv6. Since 2021 this is supported by GitHub Pages (see [here](https://github.blog/changelog/2021-09-30-enabling-ipv6-support-for-github-pages/)) and should be relatively straightforward by adding the corresponding AAAA records from https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain.

Thanks ✌🏻

**Comment by jmattheis** [comment]
Added the AAAA records, thanks for the report:
```
$ dig gotify.net AAAA +short
2606:50c0:8000::153
2606:50c0:8001::153
2606:50c0:8003::153
2606:50c0:8002::153
```
