### ISSUE TITLE
haproxy-example improvement include timeout tunnel config option

### ISSUE THREAD

**Issue by tobinq** [gotify/website#82]
Hi,
i am new to gotify, still evaluating, but one thing seems to be missing in the docs/example:
https://github.com/gotify/website/blob/master/docs/haproxy.md

with only "client" "connect" and "server" timeouts configured as in the example, i experienced quick disconnections while my gotify app on the phone then showed to reconnect in a minute and push messages were of course delayed until reconnection.

Using "timeout tunnel 1h" (1h suggested by haproxy docu) these disconnections seemed to vanish, also worth noting could be haproxies "timeout client-fin 30s" setting which haproxy docu suggests to be set together with the tunnel setting.

from haproxy docu:

> [timeout tunnel](http://docs.haproxy.org/2.9/configuration.html#4.2-timeout%20tunnel) <timeout>
> Set the maximum inactivity time on the client and server side for tunnels.
> The tunnel timeout applies when a bidirectional connection is established
between a client and a server, and the connection remains inactive in both
directions. This timeout supersedes both the client and server timeouts once
the connection becomes a tunnel. In TCP, this timeout is used as soon as no
analyzer remains attached to either connection (e.g. tcp content rules are
accepted). In HTTP, this timeout is used when a connection is upgraded (e.g.
when switching to the WebSocket protocol, or forwarding a CONNECT request
to a proxy), or after the first response when no keepalive/close option is
specified.

My suggestion is to add this to the example, or maybe at least point out that this config option exists. 
```
defaults
        # tunnels/websockes should have longer timeouts to prevent too early disconnects
        timeout tunnel  1h
        # handle non-responding clients AFTER a disconnection was sent
        timeout client-fin 30s
```

I have placed it into the defaults section of my haproxy config but it could also be placed in the backend (or listen) sections separately.

**Comment by jmattheis** [comment]
I cannot reproduce these disconnect. Gotify, if not configured otherwise, will send pings every 45 seconds. I've tried both chrome and the android app and the connection stays active without disconnects.

I've added client-fin to the docs.
