### ISSUE TITLE
go: -d flag is deprecated. -d=true is a no-op

### ISSUE THREAD

**Issue by tessus** [gotify/website#89]
In https://github.com/gotify/website/blob/master/docs/dev-setup.md

```
export GO111MODULE=on
make download-tools
go get -d
```

results in:

```
go: -d flag is deprecated. -d=true is a no-op
```

I don't really know the go toolchain, but the docs should be adjusted accordingly.

**Comment by jmattheis** [comment]
Thanks. This shouldn't be needed so I've removed it.

**Comment by tessus** [comment]
Thanks for the update!
